spring:
  datasource:
    url: postgresql://postgres:hADFaFVqIstSackIvAZsqxGUWpHJqYTa@postgres.railway.internal:5432/railway
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
